name: ssvlm
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - pandas
  - tqdm
  - scikit-learn
  - pillow
  - matplotlib
  - jupyter
  - notebook
  - pip:
      - --extra-index-url https://download.pytorch.org/whl/cu121
      - torch
      - torchvision
      - timm
      - transformers
      - accelerate
      - opencv-python
      - grad-cam
      - bitsandbytes
